version: '3.9'

services:
  db:
    image: postgres:13-alpine
    container_name: medical_appointment
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=medical_appointment
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev-db@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=root123
    restart: always
volumes:
  dev-db-data:
